service:
  name: serverless-api-learning-1
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: ${opt:stage, 'local'}
  profile: default
  environment:
    STAGE: ${self:provider.stage}
    MYSQL_HOST: ${self:custom.mysqlHost.${self:provider.stage}}
    MYSQL_DATABASE: ${self:custom.mysqlDatabase.${self:provider.stage}}
    MYSQL_USER: ${self:custom.mysqlUser.${self:provider.stage}}
    MYSQL_PASS: ${self:custom.mysqlPass.${self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  getMessages:
    handler: handler.getMessages
    memorySize: 128
    description: Get all messages
    events:
      - http:
          method: get
          path: getMessages

custom:
  mysqlHost:
    local: ${file(env.yml):LOCAL_MYSQL_HOST}
    dev: ${file(env.yml):DEV_MYSQL_HOST}
    prod: ${file(env.yml):PROD_MYSQL_HOST}
  mysqlDatabase:
    local: ${file(env.yml):LOCAL_MYSQL_DATABASE}
    dev: ${file(env.yml):DEV_MYSQL_DATABASE}
    prod: ${file(env.yml):PROD_MYSQL_DATABASE}
  mysqlUser:
    local: ${file(env.yml):LOCAL_MYSQL_USER}
    dev: ${file(env.yml):DEV_MYSQL_USER}
    prod: ${file(env.yml):PROD_MYSQL_USER}
  mysqlPass:
    local: ${file(env.yml):LOCAL_MYSQL_PASS}
    dev: ${file(env.yml):DEV_MYSQL_PASS}
    prod: ${file(env.yml):PROD_MYSQL_PASS}
