service:
  name: serverless-api-learning-1
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile: default
  environment:
    STAGE: ${self:provider.stage}
    MYSQL_HOST: ${file(env.yml):MYSQL_HOST}
    MYSQL_DATABASE: ${file(env.yml):MYSQL_DATABASE}
    MYSQL_USER: ${file(env.yml):MYSQL_USER}
    MYSQL_PASS: ${file(env.yml):MYSQL_PASS}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  hello:
    handler: handler.getMessages
    events:
      - http:
          method: get
          path: getMessages
  
custom:
  mysqlHost:
    local: ${file(env.yml):LOCAL_MYSQL_HOST}
    dev: ${file(env.yml):DEV_MYSQL_HOST}
    prod: ${file(env.yml):PROD_MYSQL_HOST}
  mysqlDatabase:
    local: ${file(env.yml):LOCAL_MYSQL_DATABASE}
    dev: ${file(env.yml):DEV_MYSQL_DATABASE}
    prod: ${file(env.yml):PROD_MYSQL_DATABASE}
  mysqlUser:
    local: ${file(env.yml):LOCAL_MYSQL_USER}
    dev: ${file(env.yml):DEV_MYSQL_USER}
    prod: ${file(env.yml):PROD_MYSQL_USER}
  mysqlPass:
    local: ${file(env.yml):LOCAL_MYSQL_PASS}
    dev: ${file(env.yml):DEV_MYSQL_PASS}
    prod: ${file(env.yml):PROD_MYSQL_PASS}